export const GET_DRIVERS_REQUEST = 'GET_DRIVERS_REQUEST'
export const GET_DRIVERS_SUCCESS = 'GET_DRIVERS_SUCCESS'
export const GET_DRIVERS_ERORR = 'GET_DRIVERS_REQUEST'

export const GET_TRIPS_REQUEST = 'GET_TRIPS_REQUEST'
export const GET_TRIPS_SUCCESS = 'GET_TRIPS_SUCCESS'
export const GET_TRIPS_ERROR = 'GET_TRIPS_ERROR'